//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagementSystem.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Location { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Device> Devices { get; set; }
    }
}
